name: 'Docker deploy to GitHub'

on:
  push:
    branches:
      - dockerized

env:
  # GitHub settings
  REGISTRY: ghcr.io/liquality

  # AWS settings
  AWS_REGION: 'us-east-1'

  # Docker image settings
  API_IMAGE_NAME: 'electrs-batch-api'
  API_IMAGE_TAG: 'latest'

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Build, tag, and push Docker image
      - name: Build, tag, push image to GitHub
        id: build-api-image
        run: |
          echo "Building and tagging Docker image ($API_IMAGE_NAME)"
          docker build -t $API_IMAGE_NAME . --no-cache
          docker tag $API_IMAGE_NAME:$API_IMAGE_TAG $REGISTRY/$API_IMAGE_NAME:$API_IMAGE_TAG
          echo "Pushing image to registry as: $REGISTRY/$API_IMAGE_NAME"
          docker push $REGISTRY/$API_IMAGE_NAME:$API_IMAGE_TAG
